[project]
name = "task-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "fastapi-mcp>=0.3.4",
    "mangum>=0.19.0",
    "pip>=25.1.1",
    "uvicorn>=0.34.3",
]
